// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP50xrCFU_ttkfq5x4_schWS7eJRYaYCM',
    appId: '1:881569677214:web:0ca96f9c68c3240066a08f',
    messagingSenderId: '881569677214',
    projectId: 'pizzeria-mamma-mia-30531',
    authDomain: 'pizzeria-mamma-mia-30531.firebaseapp.com',
    storageBucket: 'pizzeria-mamma-mia-30531.firebasestorage.app',
    measurementId: 'G-K2QV8ZSM5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0oKcjMFCPKLJRiZsELZufvkFXcsRpMSQ',
    appId: '1:881569677214:android:1cc4961234ae32e766a08f',
    messagingSenderId: '881569677214',
    projectId: 'pizzeria-mamma-mia-30531',
    storageBucket: 'pizzeria-mamma-mia-30531.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP50xrCFU_ttkfq5x4_schWS7eJRYaYCM',
    appId: '1:881569677214:web:7cb98246d17c16eb66a08f',
    messagingSenderId: '881569677214',
    projectId: 'pizzeria-mamma-mia-30531',
    authDomain: 'pizzeria-mamma-mia-30531.firebaseapp.com',
    storageBucket: 'pizzeria-mamma-mia-30531.firebasestorage.app',
    measurementId: 'G-BZ06CF4ZEP',
  );

}